import { motion, useReducedMotion } from 'framer-motion';
import { SectionHeading } from '@/components/ui/SectionHeading';

export const About = () => {
  const shouldReduceMotion = useReducedMotion();

  return (
    <section id="about" className="border-t border-granite-400/20 py-20">
      <div className="container mx-auto px-4">
        <SectionHeading title="Who You’re Working With" />

        <div className="mx-auto grid max-w-5xl items-center gap-10 md:grid-cols-[280px_1fr] lg:gap-14">
          <motion.div
            initial={shouldReduceMotion ? false : { opacity: 0, x: -20 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="mx-auto w-full max-w-[280px]"
          >
            <div className="overflow-hidden rounded-2xl bg-gradient-to-br from-pine-100 to-ridge-100 shadow-xl">
              {/*
                The column is capped at 280px, so `sizes` is fixed and the 840w
                variant only ever serves 3x displays. Generated by
                scripts/optimize-images.mjs from the 1024x1536 source PNG.
                Intrinsic width/height are the 2x variant's, purely so the
                browser can reserve the box before the bytes land.
              */}
              <picture>
                <source
                  type="image/webp"
                  sizes="280px"
                  srcSet="/images/profile/cyrus-portfolio-280w.webp 280w, /images/profile/cyrus-portfolio-560w.webp 560w, /images/profile/cyrus-portfolio-840w.webp 840w"
                />
                <img
                  src="/images/profile/cyrus-portfolio-560w.jpg"
                  sizes="280px"
                  srcSet="/images/profile/cyrus-portfolio-280w.jpg 280w, /images/profile/cyrus-portfolio-560w.jpg 560w, /images/profile/cyrus-portfolio-840w.jpg 840w"
                  alt="Cyrus Khiabani"
                  width={560}
                  height={840}
                  loading="lazy"
                  decoding="async"
                  className="aspect-[4/5] w-full object-cover"
                />
              </picture>
            </div>
          </motion.div>

          <motion.div
            initial={shouldReduceMotion ? false : { opacity: 0, x: 20 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="space-y-4 text-lg leading-relaxed text-granite-700"
          >
            <p>
              I’m Cyrus, a full-stack developer and AI engineer based on the New Jersey Shore.
              I build production automation for construction operations and personal health, where
              access, reliability, and human judgment matter.
            </p>
            <p>
              You work directly with me from the first workflow map through deployment and handoff.
            </p>
          </motion.div>
        </div>
      </div>
    </section>
  );
};
